project:
  type: book
  execute-dir: project
  resources:
    - styles/**

book:
  language: es
  sidebar:
    logo: styles/logo.png
    logo-alt: SRK Consulting logo
    search: true

format:
  html:
    page-layout: article
    brand: styles/_brand.yml
    theme: styles/theme.scss
    logo: styles/logo.png
    title-block-banner: true
    bread-crumbs: false
    filters:
      - lua/page-footer.lua
    toc: true
    toc-depth: 4
    toc-expand: true
    toc-location: left
    number-sections: false
    number-depth: 4
    highlight-style: a11y
    code-fold: true
    code-summary: "Código"
    code-line-numbers: true
    code-copy: false
    code-overflow: scroll
    link-citations: true
    link-external-newwindow: true
    anchor-sections: true
    embed-resources: false
    self-contained: false
    fig-width: 7
    fig-height: 5
    math: true
    math-output: mathjax
