## <br>`r if (exists("TITLE", inherits = FALSE)) TITLE else "ANCOLD Design Criteria"`

```{r}
#| include: false
root <- normalizePath(here::here())
.SITE <- .currentTarget("siteID.target")
.STEM <- paste0(tolower(.SITE), "-ancold")
.VARS <- list(
  Standard.target = "ANCOLD",
  ID.target = .currentTarget("ID.target"),
  siteID.target = .SITE
)
.VARS <- .VARS[lengths(.VARS) > 0L]
```

:::{.panel-tabset .full-width}

### Criteria

```{r}
#| echo: false
#| results: asis
NGR::knitBlock(
  path = "/_tbl/ancold.qmd",
  stem = .STEM,
  labels = "rewrite",
  vars = .VARS,
  root = root
)
```

### UHS

```{r}
#| echo: false
#| results: asis
NGR::knitBlock(
  path = "/_fig/DEQ.operation.qmd",
  stem = paste0(.STEM, "-obe"),
  labels = "rewrite",
  vars = .VARS,
  root = root
)
```

```{r}
#| echo: false
#| results: asis
NGR::knitBlock(
  path = "/_fig/DEQ.closure.qmd",
  stem = paste0(.STEM, "-see"),
  labels = "rewrite",
  vars = .VARS,
  root = root
)
```

### PGA

```{r}
#| echo: false
#| results: asis
NGR::knitBlock(
  path = "/_tbl/DEQ.qmd",
  stem = paste0(.STEM, "-pga"),
  labels = "rewrite",
  vars = .VARS,
  root = root
)
```

:::

```{r}
#| include: false
rm(list = intersect(c("TITLE", ".SITE", ".STEM", ".VARS"), ls()))
```
