if (!exists("projectRoot", inherits = FALSE)) {
  stop("projectRoot must be defined before loading calculation functions.", call. = FALSE)
}
projectRoot <- normalizePath(projectRoot, mustWork = TRUE)

source(file.path(projectRoot, "scripts", "setup", "utils.R"))
source(file.path(projectRoot, "scripts", "R", "ringDirect.R"))
source(file.path(projectRoot, "scripts", "R", "thetaMesh.R"))
source(file.path(projectRoot, "scripts", "R", "ringLoads.R"))
source(file.path(projectRoot, "scripts", "R", "prismThrust.R"))
source(file.path(projectRoot, "scripts", "R", "aashtoCorrugatedConduit.R"))
source(file.path(projectRoot, "scripts", "R", "ringInteraction.R"))
source(file.path(projectRoot, "scripts", "R", "externalInteraction.R"))
source(file.path(projectRoot, "scripts", "R", "k0Models.R"))
source(file.path(projectRoot, "scripts", "R", "corrugatedSection.R"))
source(file.path(projectRoot, "scripts", "R", "liningSections.R"))
source(file.path(projectRoot, "scripts", "R", "reinforcementMesh.R"))
source(file.path(projectRoot, "scripts", "R", "sectionResultants.R"))
source(file.path(projectRoot, "scripts", "R", "coverInteractionScenario.R"))
source(file.path(projectRoot, "scripts", "R", "aisiS100Demand.R"))
source(file.path(projectRoot, "scripts", "R", "concreteDemand.R"))
source(file.path(projectRoot, "scripts", "R", "concreteAciShell.R"))
source(file.path(projectRoot, "scripts", "R", "concreteAci31825.R"))
source(file.path(projectRoot, "scripts", "R", "concreteReinforcementStudy.R"))
source(file.path(projectRoot, "scripts", "R", "coverScenarios.R"))
source(file.path(projectRoot, "scripts", "R", "calculationData.R"))
source(file.path(projectRoot, "scripts", "R", "calculationClassicalComparison.R"))
source(file.path(projectRoot, "scripts", "R", "coverCalculationData.R"))
source(file.path(projectRoot, "scripts", "R", "coverConfiguration.R"))
source(file.path(projectRoot, "scripts", "R", "coverCase.R"))
