&nbsp;

```{r}
#| include: false
if (!exists("CAP", inherits = FALSE)) CAP <- readCaption("tbl.ancold")
root <- here::here()
if (!exists("AncoldTable", inherits = FALSE)) {
  AncoldTable <- data.table(
    "Class" = c("Low", "Significant", "High C", "High B", "High A", "Extreme"
    ),
    "PAR" = c("0", "1–10", "11–100", "101–1,000", ">1,000 (up to a few thousand)",
    "> several thousand"),
    "Consequences" = c("No expected loss of life; negligible off‑site impact.",
    "Few persons at risk; minor off‑site or environmental impact.",
    "Possible loss of life; moderate environmental/economic impact.",
    "Likely multiple fatalities; major environmental/economic loss.",
    "Likely multiple fatalities; regional/catastrophic impact.",
    "Very high loss of life expected; catastrophic, long‑term impacts."
    ),
    "OBE" = c("1/475", "1/475", "1/475–1/1,000", "1/475–1/1,000", "1/475–1/1,000",
    "1/475–1/1,000"),
    "SEE" = c("1/1,000", "1/1,000", "1/2,000", "1/5,000", "1/10,000", "Greater of MCE or 1/10,000 (85th percentile)"
    )
  )
}
```

```{r}
#| include: true
#| label: tbl-ancold
#| tbl-cap: !expr CAP
#|
source(file.path(root, "scripts", "tbl", "ancold.R"))
TBL
```

```{r}
#| include: false
rm(list = intersect(c("CAP", "AncoldTable"), ls()))
```
&nbsp;
